spring:
  main:
    web-application-type: none
    allow-circular-references: true
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3308/mcpdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
    mcp:
      server:
        stdio: true
        name: db-assistant

logging:
  level:
    root: OFF